export const Routes = [
  {
    id: 0,
    projectTitle: "Pomodoro Timer",
    arrayOfClasses: ["p11", "p12", "p13"],
    left: true,
    path: "/portfolioLiveTest/projects/first",
    live: "https://krystiano13.github.io/pomodoro/",
    code: "https://github.com/krystiano13/pomodoro_src",
    animation: "mars",
  },
  {
    id: 1,
    projectTitle: "Memberbase",
    arrayOfClasses: ["p21", "p22", "p23"],
    left: false,
    path: "/portfolioLiveTest/projects/second",
    live: "https://krystiano13.github.io/memberbase/",
    code: "https://github.com/krystiano13/memberbase_src",
    animation: "jupiter",
  },
  {
    id: 2,
    projectTitle: "Propel Your Business",
    arrayOfClasses: ["p31", "p32", "p33"],
    left: true,
    path: "/portfolioLiveTest/projects/third",
    live: "https://krystiano13.github.io/propel/",
    code: "https://github.com/krystiano13/propel",
    animation: "saturn",
  },
];